name = "initflow"
main = "build/server/index.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "build/server/index.js"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"

[env.production]
name = "initflow-production"

[env.staging]
name = "initflow-staging"
route = "staging.initflow.tech/*"

[env.development]
name = "initflow-dev"
route = "dev.initflow.tech/*"
