name = "initflow"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./build/client"

[build]
command = "npm run build"

# For Remix + Cloudflare Pages, we don't need build.upload settings
# as they are automatically handled by the Pages integration

# Optional: Uncomment and configure if you're using R2
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[env.production]
name = "initflow-production"

[env.staging]
name = "initflow-staging"
route = "staging.initflow.tech/*"

[env.development]
name = "initflow-dev"
route = "dev.initflow.tech/*"
