# wrangler.toml
name = "initflow"
main = "./build/worker/index.js"
compatibility_date = "2024-09-23"

[build]
command = "npm run build"

[site]
bucket = "build/client"

# Enable Node.js compatibility
node_compat = true

# Enable Node.js built-in modules compatibility
compatibility_flags = ["nodejs_compat"]
