name = "initflow"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]
main = "build/server/index.js"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

# For Remix + Cloudflare Pages, we don't need build.upload settings
# as they are automatically handled by the Pages integration

# Optional: Uncomment and configure if you're using R2
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
